/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "client_define_constants.h"

namespace client {

const client_defineConstants g_client_define_constants;

client_defineConstants::client_defineConstants() {
}

} // namespace

