/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef client_define_CONSTANTS_H
#define client_define_CONSTANTS_H

#include "client_define_types.h"

namespace client {

class client_defineConstants {
 public:
  client_defineConstants();

};

extern const client_defineConstants g_client_define_constants;

} // namespace

#endif
