/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "server_define_constants.h"

namespace server {

const server_defineConstants g_server_define_constants;

server_defineConstants::server_defineConstants() {
}

} // namespace

