/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef server_define_CONSTANTS_H
#define server_define_CONSTANTS_H

#include "server_define_types.h"

namespace server {

class server_defineConstants {
 public:
  server_defineConstants();

};

extern const server_defineConstants g_server_define_constants;

} // namespace

#endif
