// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map.proto

#ifndef PROTOBUF_map_2eproto__INCLUDED
#define PROTOBUF_map_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_map_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsMyMap_MEntry_DoNotUseImpl();
void InitDefaultsMyMap_MEntry_DoNotUse();
void InitDefaultsMyMapImpl();
void InitDefaultsMyMap();
inline void InitDefaults() {
  InitDefaultsMyMap_MEntry_DoNotUse();
  InitDefaultsMyMap();
}
}  // namespace protobuf_map_2eproto
class MyMap;
class MyMapDefaultTypeInternal;
extern MyMapDefaultTypeInternal _MyMap_default_instance_;
class MyMap_MEntry_DoNotUse;
class MyMap_MEntry_DoNotUseDefaultTypeInternal;
extern MyMap_MEntry_DoNotUseDefaultTypeInternal _MyMap_MEntry_DoNotUse_default_instance_;

// ===================================================================

class MyMap_MEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<MyMap_MEntry_DoNotUse, 
    ::google::protobuf::int64, ::google::protobuf::int64,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<MyMap_MEntry_DoNotUse, 
    ::google::protobuf::int64, ::google::protobuf::int64,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
    0 > SuperType;
  MyMap_MEntry_DoNotUse();
  MyMap_MEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const MyMap_MEntry_DoNotUse& other);
  static const MyMap_MEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const MyMap_MEntry_DoNotUse*>(&_MyMap_MEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class MyMap : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MyMap) */ {
 public:
  MyMap();
  virtual ~MyMap();

  MyMap(const MyMap& from);

  inline MyMap& operator=(const MyMap& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MyMap(MyMap&& from) noexcept
    : MyMap() {
    *this = ::std::move(from);
  }

  inline MyMap& operator=(MyMap&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MyMap& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MyMap* internal_default_instance() {
    return reinterpret_cast<const MyMap*>(
               &_MyMap_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(MyMap* other);
  friend void swap(MyMap& a, MyMap& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MyMap* New() const PROTOBUF_FINAL { return New(NULL); }

  MyMap* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MyMap& from);
  void MergeFrom(const MyMap& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MyMap* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int64, int64> m = 1;
  int m_size() const;
  void clear_m();
  static const int kMFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >&
      m() const;
  ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >*
      mutable_m();

  // @@protoc_insertion_point(class_scope:MyMap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      MyMap_MEntry_DoNotUse,
      ::google::protobuf::int64, ::google::protobuf::int64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      0 > m_;
  mutable int _cached_size_;
  friend struct ::protobuf_map_2eproto::TableStruct;
  friend void ::protobuf_map_2eproto::InitDefaultsMyMapImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MyMap

// map<int64, int64> m = 1;
inline int MyMap::m_size() const {
  return m_.size();
}
inline void MyMap::clear_m() {
  m_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >&
MyMap::m() const {
  // @@protoc_insertion_point(field_map:MyMap.m)
  return m_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >*
MyMap::mutable_m() {
  // @@protoc_insertion_point(field_mutable_map:MyMap.m)
  return m_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_map_2eproto__INCLUDED
